# Generated by Django 3.2.7 on 2021-11-04 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumTitle', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='pic',
            name='title',
        ),
        migrations.AlterField(
            model_name='pic',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pic',
            name='albumTitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='album.albumtitle'),
        ),
    ]
